# version: "3"
name: asco-resistance-andon
services:
  nuxt-app:
    build:
      context: .
      dockerfile: ./services/nuxt-app/Dockerfile
    container_name: nuxt-app
    env_file:
      - .env # USE ENVIRONMENTAL VARIABLES FILE FOR NUXT APP
    ports:
      - "3000:3000" # FRONT-END PORT
    restart: unless-stopped
  node-red:
    build:
      context: .
      dockerfile: ./services/node-red/Dockerfile
    depends_on:
      - nuxt-app
    container_name: node-red
    ports:
      - "53:53" # DNS PORT?
      - "1433:1433" # MSSQL PORT
      - "1880:1880" # BACKEND PORT
      - "5100:5100" # HANDHELD SCANNER PORT
      - "5200:5200" # HIOKI RESISTANCE METER PORT
    restart: unless-stopped
